### ISSUE TITLE
Look into lock_timeout 

### ISSUE THREAD

**Issue by shayonj** [shayonj/pg-online-schema-change#16]
During the swap, we will need to be knowledgeable of any other long queries happening against the primary table. In which case, should we set a `lock_timeout` and cancel other queries? 

Is there a better experience? - 
- maybe wait for 5 mins and retry upto 3 times before cancelling other queries? (`--wait-timeout`)
- or fail hard if `pgosc` couldn't acquire a lock for the swap perhaps? (continue replaying during this time). 
  - If failing hard, then `pgosc` should do the  cleanup. 
  - Introducing a flag to convey user preference is also possible
  - Similar to pg_repack? (re-purposing the lessons?) (combination of `--no-kill-backend` and `--wait-timeout`)

**Comment by shayonj** [comment]
There few different paths, gonna think a bit more. @jfrost (if you fancy a brainstorm), I'd be curious for your thoughts (no rush ofc) 🙏🏾 .

**Comment by jfrost** [comment]
I vote for the third option.

**Comment by shayonj** [comment]
I have the approach described here - https://github.com/shayonj/pg-online-schema-change/pull/23

Lmk if you anticipate any concerns, early stress tests came positive 🙌🏾
